Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2023-10, with the labels that each got.

#359 Remove wire cutting module
  circuit_knitting/cutting/wire_cutting.py
  circuit_knitting_toolbox/circuit_cutting/__init__.py
  pyproject.toml
  releasenotes/notes/remove-wire-cutting-ad0e7ab8af699561.yaml
Labels: cutqc, code quality

#431 Use single gate (`SXGate`) to rotate from Z to Y measurement basis
  circuit_knitting/cutting/cutting_experiments.py
  circuit_knitting/cutting/qpd/qpd.py
  test/cutting/qpd/test_qpd_basis.py
Labels: cutting

#423 Remove upper version bound on scipy
  pyproject.toml
Labels: dependencies, stable backport potential

#419 Enable pylint's `unused-argument` check
  circuit_knitting/cutting/cutqc/wire_cutting.py
  circuit_knitting/cutting/qpd/qpd.py
  circuit_knitting/utils/simulation.py
  docs/circuit_cutting/cutqc/tutorials/tutorial_3_cutting_with_quantum_serverless.ipynb
  tox.ini
Labels: code quality

#430 Don't overcount expanded sum terms in documentation
  circuit_knitting/cutting/cutting_experiments.py
  circuit_knitting/cutting/cutting_reconstruction.py
  circuit_knitting/forging/cholesky_decomposition.py
Labels: documentation

#426 Provide a workaround to #422, Sampler failing when no measurements
  circuit_knitting/cutting/cutting_experiments.py
  test/cutting/test_cutting_roundtrip.py
Labels: cutting, stable backport potential

#435 Temporarily pin qiskit-nature < 0.7
  pyproject.toml
  releasenotes/notes/qiskit-nature-pinned-c359e3933bfef993.yaml
Labels: dependencies, forging

#441 Clean up roundtrip tests
  test/cutting/test_cutting_roundtrip.py
  test/cutting/test_cutting_workflows.py
Labels: tests, cutting, code quality

#434 Swap register order, removing need to pass `num_qpd_bits`
  circuit_knitting/cutting/cutting_evaluation.py
  circuit_knitting/cutting/cutting_experiments.py
  circuit_knitting/cutting/cutting_reconstruction.py
  circuit_knitting/cutting/qpd/qpd.py
  docs/circuit_cutting/how-tos/how_to_specify_cut_wires.ipynb
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb
  docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
  releasenotes/notes/register_order_swapped-5b07fb661c6250f9.yaml
  test/cutting/test_cutting_evaluation.py
  test/cutting/test_cutting_experiments.py
  test/cutting/test_cutting_reconstruction.py
  test/cutting/test_cutting_roundtrip.py
  test/cutting/test_cutting_workflows.py
Labels: cutting

#437 Migrate from `qiskit.algorithms` to `qiskit-algorithms` package
  circuit_knitting/forging/entanglement_forging_ground_state_solver.py
  docs/entanglement_forging/tutorials/tutorial_1_getting_started.ipynb
  docs/entanglement_forging/tutorials/tutorial_2_forging_with_quantum_serverless.ipynb
  pyproject.toml
  releasenotes/notes/qiskit-algorithms-ec3fe782619bab45.yaml
  test/forging/test_entanglement_forging_ground_state_solver.py
Labels: dependencies, forging

#369 Remove ckt
  circuit_knitting_toolbox/README.md
  circuit_knitting_toolbox/__init__.py
  circuit_knitting_toolbox/circuit_cutting/__init__.py
  circuit_knitting_toolbox/entanglement_forging/__init__.py
  docs/conf.py
  pyproject.toml
  releasenotes/notes/remove-ckt-path-2386dc156b1ed9ca.yaml
  test/cutting/test_backwards_compatibility.py
  tox.ini
Labels: code quality
