Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2023-07, with the labels that each got.

#292 Add support for cut `ECRGate`
  circuit_knitting/cutting/qpd/qpd.py
  releasenotes/notes/additional-gates-f4ed6c0e8dc3a9be.yaml
  test/cutting/qpd/test_qpd.py
  test/cutting/test_cutting_roundtrip.py
Labels: enhancement, cutting

#294 Add support for `SwapGate`, `iSwapGate`, and `DCXGate`
  circuit_knitting/cutting/qpd/qpd.py
  releasenotes/notes/additional-gates-f4ed6c0e8dc3a9be.yaml
  test/cutting/qpd/test_qpd.py
  test/cutting/qpd/test_qpd_basis.py
  test/cutting/test_cutting_roundtrip.py
Labels: enhancement, cutting

#308 Configure Intersphinx to docs
  circuit_knitting/cutting/cutting_evaluation.py
  docs/conf.py
Labels: documentation

#255 Return a mixture of exact and sampled weights as appropriate
  circuit_knitting/cutting/__init__.py
  circuit_knitting/cutting/cutting_evaluation.py
  circuit_knitting/cutting/qpd/__init__.py
  circuit_knitting/cutting/qpd/qpd.py
  docs/circuit_cutting/how-tos/how_to_generate_exact_sampling_coefficients.ipynb
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb
  releasenotes/notes/generate-qpd-weights-mixture-79c1c420105c8564.yaml
  test/cutting/qpd/test_qpd.py
Labels: enhancement, quantum performance, cutting

#316 don't enumerate figures and code snippets
  docs/conf.py
Labels: documentation

#317 Run slow tests for coverage only
  tox.ini
Labels: cicd

#322 improve ObservableCollection.lookup docstring
  circuit_knitting/utils/observable_grouping.py
Labels: documentation

#327 Shorten the section names in the docs
  docs/index.rst
Labels: documentation

#325 Cplex is now compatible with Python 3.11
  .github/workflows/test_latest_versions.yml
  INSTALL.rst
  pyproject.toml
Labels: dependencies, tests

#328 Migrate to Docker Compose V2
  .github/workflows/README.md
  .github/workflows/docker.yml
  INSTALL.rst
  compose.yaml
Labels: cicd

#315 Update freezing orbitals documentation
  circuit_knitting/forging/entanglement_forging_ground_state_solver.py
  docs/entanglement_forging/explanation/index.rst
  docs/entanglement_forging/how-tos/freeze-orbitals.ipynb
Labels: documentation, forging

#331 Bump Python version in Dockerfile to 3.11
  Dockerfile
Labels: dependencies

#332 Fix formatting of example in `reduce_bitstrings` docstring
  circuit_knitting/utils/orbital_reduction.py
Labels: documentation

#302 Implement cutting of general 2-qubit unitaries
  README.md
  circuit_knitting/cutting/__init__.py
  circuit_knitting/cutting/qpd/__init__.py
  circuit_knitting/cutting/qpd/qpd.py
  circuit_knitting/cutting/qpd/qpd_basis.py
  docs/circuit_cutting/explanation/index.rst
  releasenotes/notes/additional-gates-f4ed6c0e8dc3a9be.yaml
  releasenotes/notes/supported-gates-d2156f58bc07fc7a.yaml
  test/cutting/qpd/test_qpd.py
  test/cutting/qpd/test_qpd_basis.py
  test/cutting/test_cutting_roundtrip.py
Labels: enhancement, cutting

#338 Make the repository link more obvious from the Sphinx build
  docs/conf.py
  docs/index.rst
Labels: documentation

#339 Add README badge linking to stable documentation
  README.md
Labels: documentation

#340 Update README.md
  test/README.md
Labels: documentation

#337 Add `SECURITY.md`
  SECURITY.md
Labels: documentation
