Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2023-06, with the labels that each got.

#228 Add documentation of the different tox environments
  test/README.md
Labels: documentation

#229 Update workflows README (add missing workflows)
  .github/workflows/README.md
Labels: documentation

#58 Remove Qiskit Runtime retry loop
  circuit_knitting_toolbox/entanglement_forging/entanglement_forging_knitter.py
Labels: forging

#232 Add backwards compatibility tests of 0.2 circuit cutting workflows
  test/circuit_cutting/test_backwards_compatibility.py
  test/conftest.py
  tox.ini
Labels: tests, cutting

#233 Rename the tutorials to order by number & enable redirects to prevent link rot
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb
  docs/circuit_cutting/tutorials/README.rst
  docs/conf.py
  pyproject.toml
Labels: documentation

#147 Enable ruff for jupyter notebooks
  .ruff.toml
  docs/circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.ipynb
  docs/circuit_cutting/cutqc/tutorials/tutorial_2_manual_cutting.ipynb
  docs/circuit_cutting/cutqc/tutorials/tutorial_3_cutting_with_quantum_serverless.ipynb
  docs/entanglement_forging/how-tos/freeze-orbitals.ipynb
  docs/entanglement_forging/how-tos/use-asymmetric-bitstrings.ipynb
  docs/entanglement_forging/tutorials/tutorial_1_getting_started.ipynb
  docs/entanglement_forging/tutorials/tutorial_2_forging_with_quantum_serverless.ipynb
  pyproject.toml
  tox.ini
Labels: code quality

#246 Enable tests on Windows
  .github/workflows/test_latest_versions.yml
  README.md
  test/forging/test_entanglement_forging_ground_state_solver.py
  test/forging/test_entanglement_forging_knitter.py
Labels: tests

#263 Export `qpdbasis_from_gate` from `qpd` module
  circuit_knitting/cutting/qpd/__init__.py
Labels: qpd

#249 Add note on samping overhead to cutting tutorials
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb
Labels: documentation

#270 Add installation section to readme
  README.md
Labels: documentation

#230 Suppress warnings from Qiskit Nature
  README.md
  circuit_knitting/forging/__init__.py
  circuit_knitting/forging/cholesky_decomposition.py
  circuit_knitting/forging/entanglement_forging_ground_state_solver.py
  docs/entanglement_forging/tutorials/tutorial_2_forging_with_quantum_serverless.ipynb
  pyproject.toml
  releasenotes/notes/remove-opflow-177bb07ba0e68002.yaml
  tools/extremal-python-dependencies.py
  tox.ini
Labels: forging

#269 Move configuration out of `extremal-python-dependencies`
  .github/workflows/test_development_versions.yml
  .github/workflows/test_minimum_versions.yml
  tools/extremal-python-dependencies.py
Labels: on hold

#274 Ignore opflow warnings
  pyproject.toml
  tox.ini
Labels: code quality

#267 Improve `separate_circuit` docstring
  circuit_knitting/cutting/cutqc/mip_model.py
  circuit_knitting/utils/transforms.py
  pyproject.toml
Labels: documentation, cutting

#271 Update EF how-to index
  docs/entanglement_forging/how-tos/index.rst
Labels: documentation, forging

#268 Fix bug in result creation and add instantiation of EFGSS to how-to
  circuit_knitting/forging/__init__.py
  circuit_knitting/forging/entanglement_forging_ground_state_solver.py
  docs/entanglement_forging/how-tos/freeze-orbitals.ipynb
  releasenotes/notes/ef-results-bug-5aa84ca5611dd827.yaml
Labels: bug, documentation, forging

#231 Add brief CONTRIBUTING.md
  CONTRIBUTING.md
  INSTALL.rst
  circuit_knitting_toolbox/README.md
  setup.py
  tools/extremal-python-dependencies.py
Labels: documentation

#281 Add `py-notebook` and `py3-notebook` tox environments
  tox.ini
Labels: tests

#276 Fix bug in decompose-qpd-instructions
  circuit_knitting/cutting/qpd/qpd.py
  releasenotes/notes/dx-qpd-inst-bug-fe9c50dad716b848.yaml
  test/cutting/qpd/test_qpd.py
Labels: bug, cutting

#277 Add a supported_gates function
  circuit_knitting/cutting/__init__.py
  circuit_knitting/cutting/qpd/__init__.py
  circuit_knitting/cutting/qpd/qpd.py
  releasenotes/notes/supported-gates-d2156f58bc07fc7a.yaml
  test/cutting/qpd/test_qpd.py
Labels: enhancement, cutting

#286 Add explicit numpy dependency
  pyproject.toml
  releasenotes/notes/explicit-numpy-dependency-fdd89846b37a8d4c.yaml
Labels: dependencies

#290 Add support for cut `CYGate`s and `CHGate`s
  circuit_knitting/cutting/qpd/qpd.py
  releasenotes/notes/additional-gates-f4ed6c0e8dc3a9be.yaml
  test/cutting/qpd/test_qpd.py
  test/cutting/test_cutting_roundtrip.py
Labels: enhancement, cutting
