Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2023-05, with the labels that each got.

#85 Add link from README to release notes
  README.md
  docs/index.rst
  docs/release-notes.rst
Labels: documentation

#136 Set unreleased version title in reno config
  releasenotes/config.yaml
Labels: documentation

#135 Skip slow tests by default (but not in CI)
  .github/workflows/test_development_versions.yml
  .github/workflows/test_latest_versions.yml
  .github/workflows/test_minimum_versions.yml
  test/conftest.py
  test/entanglement_forging/test_entanglement_forging_knitter.py
  tox.ini
Labels: tests

#137 Initial commit of basic QPD classes, supporting functionality, and unit tests
  circuit_knitting_toolbox/circuit_cutting/qpd/__init__.py
  circuit_knitting_toolbox/circuit_cutting/qpd/instructions/__init__.py
  circuit_knitting_toolbox/circuit_cutting/qpd/instructions/qpd_gate.py
  circuit_knitting_toolbox/circuit_cutting/qpd/instructions/qpd_measure.py
  circuit_knitting_toolbox/circuit_cutting/qpd/qpd.py
  circuit_knitting_toolbox/circuit_cutting/qpd/qpd_basis.py
  circuit_knitting_toolbox/utils/iteration.py
  pyproject.toml
  test/circuit_cutting/qpd/__init__.py
  test/circuit_cutting/qpd/instructions/test_qpd_gate.py
  test/circuit_cutting/qpd/instructions/test_qpd_measure.py
  test/circuit_cutting/qpd/test_qpd.py
  test/circuit_cutting/qpd/test_qpd_basis.py
Labels: qpd

#141 Create generate_qpd_samples function
  circuit_knitting_toolbox/circuit_cutting/qpd/__init__.py
  circuit_knitting_toolbox/circuit_cutting/qpd/qpd.py
  test/circuit_cutting/qpd/test_qpd.py
Labels: qpd

#150 Implement decompose_qpd_instructions
  circuit_knitting_toolbox/circuit_cutting/qpd/__init__.py
  circuit_knitting_toolbox/circuit_cutting/qpd/qpd.py
  test/circuit_cutting/qpd/test_qpd.py
Labels: qpd

#140 partition_circuit_qubits
  circuit_knitting_toolbox/circuit_cutting/__init__.py
  circuit_knitting_toolbox/circuit_cutting/cutting_decomposition.py
  test/circuit_cutting/test_cutting_decomposition.py
Labels: cutting

#145 Add separate_circuit, qpd_roundtrip test, and observable utils
  circuit_knitting_toolbox/circuit_cutting/cutting_decomposition.py
  circuit_knitting_toolbox/circuit_cutting/cutting_evaluation.py
  circuit_knitting_toolbox/circuit_cutting/cutting_reconstruction.py
  circuit_knitting_toolbox/utils/bitwise.py
  circuit_knitting_toolbox/utils/observable_grouping.py
  circuit_knitting_toolbox/utils/simulation.py
  circuit_knitting_toolbox/utils/transforms.py
  test/circuit_cutting/qpd/test_qpd_roundtrip.py
  test/circuit_cutting/test_cutting_evaluation.py
  test/circuit_cutting/test_cutting_reconstruction.py
  test/utils/test_iteration.py
  test/utils/test_observable_grouping.py
  test/utils/test_simulation.py
  test/utils/test_transforms.py
Labels: qpd

#156 Change `gate.operation` -> `instruction.operation`
  circuit_knitting_toolbox/circuit_cutting/cutting_decomposition.py
  circuit_knitting_toolbox/circuit_cutting/qpd/qpd.py
Labels: code quality

#160 Add `overhead` property to `QPDBasis`
  circuit_knitting_toolbox/circuit_cutting/qpd/qpd_basis.py
  test/circuit_cutting/qpd/test_qpd_basis.py
Labels: enhancement

#114 Enable monthly dependabot updates for the linters
  .github/dependabot.yml
Labels: code quality

#165 Add bibtex note to Sphinx
  CITATION.bib
  docs/index.rst
Labels: documentation

#178 Move roundtrip test out of `qpd` module
  test/circuit_cutting/test_cutting_roundtrip.py
Labels: tests

#198 Improve the API reference docs within the utils directory
  circuit_knitting_toolbox/utils/__init__.py
  circuit_knitting_toolbox/utils/bitwise.py
  circuit_knitting_toolbox/utils/conversion.py
  circuit_knitting_toolbox/utils/iteration.py
  circuit_knitting_toolbox/utils/metrics.py
  circuit_knitting_toolbox/utils/observable_grouping.py
  circuit_knitting_toolbox/utils/orbital_reduction.py
  circuit_knitting_toolbox/utils/simulation.py
  circuit_knitting_toolbox/utils/transforms.py
  tox.ini
Labels: documentation

#200 Fix the exact simulator to error on classical conditions
  circuit_knitting_toolbox/utils/simulation.py
  test/utils/test_simulation.py
Labels: exact simulator

#153 Final (0.2.0) cutting workflow
  README.md
  circuit_knitting_toolbox/circuit_cutting/__init__.py
  circuit_knitting_toolbox/circuit_cutting/cutting_decomposition.py
  circuit_knitting_toolbox/circuit_cutting/cutting_evaluation.py
  circuit_knitting_toolbox/circuit_cutting/cutting_reconstruction.py
  circuit_knitting_toolbox/circuit_cutting/qpd/__init__.py
  docs/circuit_cutting/explanation/index.rst
  docs/circuit_cutting/how-tos/README.rst
  docs/circuit_cutting/how-tos/how_to_generate_exact_quasi_dists_from_sampler.ipynb
  docs/circuit_cutting/how-tos/how_to_generate_exact_sampling_coefficients.ipynb
  docs/circuit_cutting/how-tos/index.rst
  docs/circuit_cutting/tutorials/README.rst
  docs/circuit_cutting/tutorials/gate_cutting_to_reduce_circuit_depth.ipynb
  docs/circuit_cutting/tutorials/gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/index.rst
  docs/index.rst
  pyproject.toml
  releasenotes/notes/gate-cutting-workflow-ebbedbdb1313b258.yaml
  test/circuit_cutting/test_cutting_decomposition.py
  test/circuit_cutting/test_cutting_evaluation.py
  test/circuit_cutting/test_cutting_reconstruction.py
  test/circuit_cutting/test_cutting_roundtrip.py
Labels: cutting, highly desired

#207 Remove any attempt at using the samplers in parallel
  circuit_knitting_toolbox/circuit_cutting/cutting_evaluation.py
Labels: cutting

#209 Clean up 0.2.0 release note
  releasenotes/notes/gate-cutting-workflow-ebbedbdb1313b258.yaml
Labels: documentation

#217 Tweaks to gate cutting workflow release note
  docs/circuit_cutting/explanation/index.rst
  docs/circuit_cutting/tutorials/index.rst
  releasenotes/notes/gate-cutting-workflow-ebbedbdb1313b258.yaml
Labels: documentation

#219 Ensure that each sampler passed to `samplers` is unique
  circuit_knitting_toolbox/circuit_cutting/cutting_evaluation.py
  test/circuit_cutting/test_cutting_evaluation.py
Labels: cutting

#210 Render QPD API in sphinx api docs
  circuit_knitting_toolbox/circuit_cutting/__init__.py
  circuit_knitting_toolbox/circuit_cutting/qpd/__init__.py
  circuit_knitting_toolbox/circuit_cutting/qpd/instructions/__init__.py
  docs/_templates/autosummary/class_no_inherited_members.rst
Labels: documentation

#213 Update installation instructions
  INSTALL.rst
Labels: documentation
