Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2024-06, with the labels that each got.

#616 Use batch mode correctly in the tutorials
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
Labels: documentation, stable backport potential

#581 Improve validation in the cutting reconstruction function
  circuit_knitting/cutting/cutting_reconstruction.py
  test/cutting/test_cutting_reconstruction.py
Labels: cutting

#615 Describe optimization parameters in docs
  circuit_knitting/cutting/automated_cut_finding.py
Labels: documentation, stable backport potential, cut finder

#625 transforms.py: Avoid setting the barrier to be a uuid object
  circuit_knitting/utils/transforms.py
Labels: stable backport potential

#623 Bump qiskit-ibm-runtime version and use `mode=batch`
  README.md
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
  pyproject.toml
  releasenotes/notes/bump-dependency-versions-26e93b55695c3034.yaml
Labels: dependencies
