Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2024-04, with the labels that each got.

#527 Deprecate CutQC
  circuit_knitting/cutting/cutqc/__init__.py
  circuit_knitting/cutting/cutqc/dynamic_definition.py
  circuit_knitting/cutting/cutqc/mip_model.py
  circuit_knitting/cutting/cutqc/wire_cutting.py
  circuit_knitting/cutting/cutqc/wire_cutting_evaluation.py
  circuit_knitting/cutting/cutqc/wire_cutting_post_processing.py
  circuit_knitting/cutting/cutqc/wire_cutting_verification.py
  circuit_knitting/utils/conversion.py
  circuit_knitting/utils/metrics.py
  pyproject.toml
  releasenotes/notes/deprecate-cutqc-7541c514bd96fb05.yaml
  test/cutting/test_cutqc.py
  tox.ini
Labels: cutqc

#540 Add github button to docs homepage
  docs/index.rst
Labels: stable backport potential

#537 Remove greedy recursion
  circuit_knitting/cutting/cut_finding/cco_utils.py
Labels: bug, cut finder

#534 RFC: Re-execute notebooks on CI when building Sphinx docs
  docs/conf.py
  tox.ini
Labels: documentation, cicd

#547 Fix hyper-specific import of `qiskit.synthesis.TwoQubitWeylDecomposition`
  circuit_knitting/cutting/qpd/decompositions.py
Labels: code quality

#544 Enable pylint's `dangerous-default-value` check
  circuit_knitting/cutting/cut_finding/circuit_interface.py
  circuit_knitting/cutting/cut_finding/cut_optimization.py
  circuit_knitting/cutting/cut_finding/lo_cuts_optimizer.py
  pyproject.toml
Labels: code quality

#533 Update cutqc tutorials index with deprecated status
  docs/circuit_cutting/cutqc/index.rst
  docs/circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.ipynb
  docs/circuit_cutting/cutqc/tutorials/tutorial_2_manual_cutting.ipynb
Labels: documentation, cutqc

#513 Use Qiskit Runtime `SamplerV2` in local mode instead of `BackendSamplerV2` in test
  pyproject.toml
  releasenotes/notes/bump-dependency-versions-d5dc3b10ba842f2d.yaml
  test/cutting/test_cutting_workflows.py
Labels: tests

#342 Add sampling overhead table and expand/update cutting explanation
  docs/circuit_cutting/explanation/index.rst
  releasenotes/notes/0.2/gate-cutting-workflow-ebbedbdb1313b258.yaml
  test/cutting/qpd/test_qpd.py
Labels: documentation, tests, cutting, stable backport potential

#552 Migrate tutorials and a how-to guide to v2 primitives
  docs/circuit_cutting/how-tos/how_to_specify_cut_wires.ipynb
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb
  docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
Labels: documentation, cutting

#561 Switch to `macos-13` runner so it is an Intel chip
  .github/workflows/test_latest_versions.yml
Labels: cicd

#562 Revert "Temporarily disable worktrees in docs and lint workflows (#559)"
  .github/workflows/docs.yml
  .github/workflows/lint.yml
Labels: cicd

#565 Early terminate from loops when generating cutting experiments
  circuit_knitting/cutting/cutting_experiments.py
  test/cutting/test_cutting_experiments.py
Labels: cutting

#563 Force at least one classical bit in `qpd_measurements` register
  circuit_knitting/cutting/qpd/decompose.py
  releasenotes/notes/nonzero-register-size-e112e34417ff79b9.yaml
  test/cutting/qpd/test_qpd.py
Labels: bug, cutting

#570 Remove discussion about user's compute env from knitting docs
  README.md
  docs/index.rst
Labels: documentation, stable backport potential
