Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2024-08, with the labels that each got.

#657 Edit cutting explanation
  docs/circuit_cutting/explanation/index.rst
Labels: documentation, stable backport potential

#659 Pin qiskit-ibm-runtime when running notebooks
  .github/workflows/test_development_versions.yml
  pyproject.toml
Labels: dependencies

#646 Make project's relationship with Qiskit consistent in the copyright headers
  circuit_knitting/cutting/instructions/cut_wire.py
  circuit_knitting/cutting/instructions/move.py
  circuit_knitting/cutting/qpd/instructions/qpd_gate.py
  circuit_knitting/cutting/qpd/instructions/qpd_measure.py
  circuit_knitting/cutting/wire_cutting_transforms.py
  docs/conf.py
  test/cutting/test_wire_cutting_transforms.py
Labels: stable backport potential

#662 Backport CutQC removal to `stable/0.8` branch
  .github/workflows/test_development_versions.yml
  .github/workflows/test_latest_versions.yml
  CITATION.bib
  INSTALL.rst
  README.md
  circuit_knitting/cutting/__init__.py
  circuit_knitting/cutting/cutqc/__init__.py
  circuit_knitting/cutting/cutqc/dynamic_definition.py
  circuit_knitting/cutting/cutqc/mip_model.py
  circuit_knitting/cutting/cutqc/wire_cutting.py
  circuit_knitting/cutting/cutqc/wire_cutting_evaluation.py
  circuit_knitting/cutting/cutqc/wire_cutting_post_processing.py
  circuit_knitting/cutting/cutqc/wire_cutting_verification.py
  circuit_knitting/utils/__init__.py
  circuit_knitting/utils/conversion.py
  circuit_knitting/utils/metrics.py
  compose.yaml
  docs/circuit_cutting/cutqc/README.rst
  docs/circuit_cutting/cutqc/index.rst
  docs/circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.ipynb
  docs/circuit_cutting/cutqc/tutorials/tutorial_2_manual_cutting.ipynb
  docs/index.rst
  pyproject.toml
  releasenotes/notes/remove-cutqc-fe70369bdbe65668.yaml
  test/cutting/test_cutqc.py
  tox.ini
Labels: cutqc

#665 Use `qiskit_addon_cutting.__version__` in `docs/conf.py`
  docs/conf.py
Labels: code quality
