Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2024-05, with the labels that each got.

#554 Add tests of `XXPlusYYGate` and `XXMinusYYGate` for nonzero beta parameter
  test/cutting/qpd/test_qpd.py
  test/cutting/test_cutting_roundtrip.py
Labels: tests, cutting

#580 Update authors in `CITATION.bib`
  CITATION.bib
  docs/index.rst
Labels: documentation, stable backport potential

#583 Update `CITATION.bib` to remove entanglement forging authors
  CITATION.bib
Labels: documentation, stable backport potential

#585 Avoid exploring extraneous minima in the cut-finder search space
  circuit_knitting/cutting/cut_finding/best_first_search.py
  circuit_knitting/cutting/cut_finding/cut_optimization.py
  circuit_knitting/cutting/cut_finding/lo_cuts_optimizer.py
  docs/circuit_cutting/tutorials/04_automatic_cut_finding.ipynb
  releasenotes/notes/cut-finder-enhancement-1e1d37174d7a8860.yaml
  test/cutting/cut_finding/test_best_first_search.py
  test/cutting/cut_finding/test_cut_finder_results.py
Labels: bug, enhancement, stable backport potential, cut finder

#560 Test on ARM macOS runners
  .github/workflows/test_latest_versions.yml
Labels: cicd

#595 Remove explicit dependency on ipykernel
  pyproject.toml
Labels: dependencies

#598 Tutorials: Fix typo and split cell that retrieves results
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb
  docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
Labels: documentation, stable backport potential

#607 Update README.md
  README.md
Labels: stable backport potential

#609 update tutorial readme
  docs/circuit_cutting/tutorials/README.rst
Labels: documentation, stable backport potential

#594 Remove idle wires by default when separating the circuit
  circuit_knitting/cutting/cutting_decomposition.py
  circuit_knitting/utils/transforms.py
  releasenotes/notes/rm-idle-wires-1758bf8763081a9b.yaml
  test/utils/test_transforms.py
Labels: enhancement, cutting

#586 Provide options in the cut-finder API to turn LO gate and wire cut finding off or on, expose min-reached flag.
  circuit_knitting/cutting/automated_cut_finding.py
  circuit_knitting/cutting/cut_finding/cut_optimization.py
  circuit_knitting/cutting/cut_finding/disjoint_subcircuits_state.py
  circuit_knitting/cutting/cut_finding/optimization_settings.py
  docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/circuit_cutting/tutorials/04_automatic_cut_finding.ipynb
  releasenotes/notes/min-reached-finder-flag-aa6dd9021e165f80.yaml
  releasenotes/notes/new-flags-to-control-cut-finder-search-e499e1ea49abb0bc.yaml
  test/cutting/cut_finding/test_best_first_search.py
  test/cutting/cut_finding/test_cut_finder_results.py
  test/cutting/cut_finding/test_cutting_actions.py
  test/cutting/cut_finding/test_optimization_settings.py
  test/cutting/test_find_cuts.py
Labels: enhancement, cut finder
