Repository Qiskit/qiskit-addon-cutting, pull requests merged in 2024-09, with the labels that each got.

#673 Install extremal-python-dependencies from pypi
  .github/workflows/test_development_versions.yml
  .github/workflows/test_minimum_versions.yml
  tools/extremal-python-dependencies/README.md
  tools/extremal-python-dependencies/extremal_python_dependencies/__init__.py
  tools/extremal-python-dependencies/extremal_python_dependencies/main.py
  tools/extremal-python-dependencies/pyproject.toml
  tox.ini
Labels: dependencies, cicd

#677 Remove "prototype" handling from `citation.yml` workflow
  .github/workflows/citation.yml
Labels: cicd

#674 Update release workflow
  .github/workflows/release.yml
Labels: cicd

#676 Upgrade to qiskit-sphinx-theme 2.0.0
  docs/_static/images/qiskit-dark-logo.svg
  docs/_static/images/qiskit-light-logo.svg
  docs/conf.py
  pyproject.toml
Labels: documentation

#682 Phrase tutorials as Qiskit patterns
  docs/how-tos/how_to_specify_cut_wires.ipynb
  docs/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb
  docs/tutorials/03_wire_cutting_via_move_instruction.ipynb
  docs/tutorials/04_automatic_cut_finding.ipynb
Labels: documentation, stable backport potential

#685 Fix tutorial headers
  docs/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb
  docs/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb
  docs/tutorials/03_wire_cutting_via_move_instruction.ipynb
  docs/tutorials/04_automatic_cut_finding.ipynb
Labels: documentation, stable backport potential

#686 Add link to Qiskit addons on landing pages
  README.md
  docs/index.rst
Labels: documentation, stable backport potential
